package lila.quote

import play.api.libs.json._
import scala.util.Random

final class Quote(val text: String, val author: String)

object Quote {

  def one = all(Random.nextInt(all.size))

  def one(seed: String) = all(new Random(seed.hashCode).nextInt(all.size))

  // courtesy of http://www.chess-poster.com/english/notes_and_facts/chess_quotes.htm
  // and other various sources
  val all = Vector(
    
new Quote("A bad move invites more bad moves"),
new Quote("A Pawn is worth a thousand Golds"),
new Quote("A Pawn-anchored Gold is more solid than a rock"),
new Quote("A tokin is faster than you think"),
new Quote("A Vanguard Pawn is dificult to maintain (The court noble-cannot lve up to his rank)"),
new Quote("A won game is like a devil"),
new Quote("Activate idle pieces"),
new Quote("Against a King on the edge, push the edge Pawn"),
new Quote("Against a Silver in front of its Pawns, defend with a Pawn"),
new Quote("Against a sitting King the Bishop is stronger then Rook"),
new Quote("Against Ranging Rook, aim at a Bishop's exchange"),
new Quote("Against the Mino play an edge attack"),
new Quote("Aganst a King on the first rank, the Rook on the second"),
new Quote("Aim at floating pieces"),
new Quote("Aim at the King's ears"),
new Quote("An attack with four pieces won't fail"),
new Quote("Approach the King by surrounding him"),
new Quote("Atokin on 5c cannot lose"),
new Quote("Attack is the best defence"),
new Quote("Attack with Rook, Bishop, Silver and Knight"),
new Quote("Avoid a sitting King (A sitting King is a duck)"),
new Quote("Beware of too skilful lines"),
new Quote("Castle your King after seeing where your opponent's Rook moves to"),
new Quote("Check your checks"),
new Quote("cut off the King's escape route"),
new Quote("Defend against major pieces by drawing them closer"),
new Quote("Defend the King with three generals"),
new Quote("Don´t be afraid to sacrifice major pieces"),
new Quote("Don't be afraid to sacrifice Rook or Bishop"),
new Quote("Don't put King and Rook close toget"),
new Quote("Don't put the King on the Bishop's diagonal"),
new Quote("Don't run from a fork"),
new Quote("Don't run from a fork"),
new Quote("Drive the King to the back rank"),
new Quote("drop a pawn on the focal point"),
new Quote("Drop a silver at the King's belly"),
new Quote("Drop the Knight well back"),
new Quote("Drop the Lance at a distance"),
new Quote("Drop the Lance on the back rank"),
new Quote("Drop where your opponent wants to drop"),
new Quote("Early escape is worth eight moves"),
new Quote("Entice the Gold diagonally forwards"),
new Quote("Exchanging the Rook Pawn has three advantages"),
new Quote("gainst the Yagura、the joining Pawns attack"),
new Quote("Hisshi（brinkmate）is better than mate"),
new Quote("If there is mate with a Pawn drop, there is a legal mate too"),
new Quote("If there's a loose piece, you won't be stuck for a move"),
new Quote("If you do n't have a move,push the edge Pawn"),
new Quote("if you have three pawns, joining pawn and dangling pawn"),
new Quote("In a slow game the Bishop has the leading part"),
new Quote("in Bishop Exchange, don't push the central Pawn"),
new Quote("in the endgame (rose) speed is more important than material profit"),
new Quote("In the endgame a vulgar move may be all right"),
new Quote("In the opening the Bishop is stronger than the Rook"),
new Quote("interposing makes a splendid move"),
new Quote("Just take the side-pawn"),
new Quote("keep the foothold for the attack."),
new Quote("Mend the wall Silver"),
new Quote("Move King and Rook to opposite side"),
new Quote("Oppose Bishop wth Bishop"),
new Quote("Recapture the Vanguard Pawn with the opposing Pawn"),
new Quote("Rook and King are weak at the ears"),
new Quote("Save the Gold till the end (for the coup de grace)"),
new Quote("Silver at the head of the（opponent's）Knight is the standard move"),
new Quote("Silver in front of its Pawns-quick attack, Gold behind its Pawns-slow game"),
new Quote("Squeeze (and hisshi) first, check later"),
new Quote("Start the fight with a Pawn sacrifice a pawn"),
new Quote("Take two for one, even if there is a Pawn in it"),
new Quote("The 5e Vanguard Pawn is the Tenno Mountain"),
new Quote("The bystander sees the best of the game"),
new Quote("The Dragon to the enemy camp, the Horse to your own"),
new Quote("The Knight that jumps high falls prey to a Pawn"),
new Quote("The Rook's page is the Silver"),
new Quote("The sideways action of the Rook is strong in defence"),
new Quote("There is always a move at the edge"),
new Quote("To take the side-pawn is to grasp the nettle (obs.)"),
new Quote("Use the Silver like a plover (moving zig-zag）"),
new Quote("vulgar move may be brilliant"),
new Quote("With a Gold on your back rank, you-can sacrifice the Rook"),
new Quote("With a watchtower Bishop there is bound to be a brilliant move."),
new Quote("With three Knights in hand、there must be a mate"),
new Quote("with three Pawns in hand, a joining Pawns attack or an edge attack"),
new Quote("without attack、there's no chance of winning"),
new Quote("without Gold in hand there is no defence"),
new Quote("without Pawns (in hand) the game is lost"),
new Quote("wth Gold and Silver reversed (Gold above Silver) you're bound to get trouble"),
new Quote("55 is a strategic point"),
new Quote("A clumsy Climbing Silver is no threat to the opponent"),
new Quote("A flanKing Silver is the first step to brinkmate"),
new Quote("A floating Rook attacks a retreating Rook defends"),
new Quote("A four piece mating net will always catch its prey"),
new Quote("A Horse is worth three Generals"),
new Quote("A King in front of his Knight is hard to attack"),
new Quote("A King in front of his Pawns is easy meat"),
new Quote("A Lance behind a Rook is twice as sharp"),
new Quote("A Meijin needs no joseki"),
new Quote("A Pawn is worth its weight in Gold"),
new Quote("A Ranging Rook is a good middle game move"),
new Quote("A Rook on the second rank stops a quick mate"),
new Quote("A Shogi King's home is his castle"),
new Quote("A Silver in front of an enemy Knight is joseki"),
new Quote("A Tokin on the seventh rank is diabolical"),
new Quote("A watchtower Bishop has more scope"),
new Quote("Advance Pawn and Silver side by side"),
new Quote("Against the Ranging Rook put the King on the second rank"),
new Quote("Aim at effective pieces"),
new Quote("Aim at the next good move"),
new Quote("Amateurs dream, professionals think"),
new Quote("Attacks grow from seed pieces"),
new Quote("Avoid loss of material"),
new Quote("Before dropping a Knight move it one square back"),
new Quote("Better a Pawn than a tempo."),
new Quote("Beware the peeping Bishop"),
new Quote("Bishops and Knights are weak in the head"),
new Quote("Bringthe Horse back to camp"),
new Quote("Castle befor you fight"),
new Quote("Checks don't pay"),
new Quote("Common sense is not absolute"),
new Quote("Defend the head of the Bishop with a Gold"),
new Quote("Discovered check has no defence"),
new Quote("Don't answer traps with traps"),
new Quote("Don't fear major pieces in front of their Pawns"),
new Quote("Drive the King back for an easier mate"),
new Quote("Drop major pieces at a distance"),
new Quote("Drop Pawn agains Pawn to recover position"),
new Quote("Endgames are won on confidence"),
new Quote("Even Rooks and Bishops can be sacrificed"),
new Quote("Every floating piece leaves a chink in your armour"),
new Quote("Exchange of pieces is a profit for the weaker player"),
new Quote("Fight hardest when you are behind"),
new Quote("Help is no defence"),
new Quote("If the Golds and Silvers go high let the King follow them"),
new Quote("If your pieces cry, so do you"),
new Quote("In endgames the King is the main performer"),
new Quote("In slow games switch the Bishop to the right"),
new Quote("In the fortress don't push the edge Pawn till the King is round the corner"),
new Quote("In the opening don't allow a one-sided exchange of Rook Pawns"),
new Quote("In the opening move the odd numbered Pawns"),
new Quote("Keep balance"),
new Quote("Kings follow Kings"),
new Quote("Knights and Silvers must always think twice before promoting"),
new Quote("Knights fork"),
new Quote("Knights like to be sacrificed"),
new Quote("Lance drop 8f is joseki"),
new Quote("Make a bolthole for your King"),
new Quote("Make your pieces work"),
new Quote("Never attack too soon"),
new Quote("No Golds - no mate"),
new Quote("Opening: tempo; Middle-game: profit; Endgame: speed"),
new Quote("Oppose a Reclining Silver with a Pawn or another Reclining Silver"),
new Quote("Oppose a vanguard Silver with a Pawn"),
new Quote("Oppose the enemy's right Silver"),
new Quote("Pawn strikes cause havoc in the opponent's camp"),
new Quote("Pros don't take pieces"),
new Quote("Ranging Rook needs a Static Bishop"),
new Quote("Remember Pawns can mate too"),
new Quote("Reversing Gold and Silver is vulgar style"),
new Quote("Rooks and Bishops need open lines"),
new Quote("Rooks know how to defend"),
new Quote("Sacrifice - the key to mate"),
new Quote("Silvers before Golds"),
new Quote("Suport a vanguard Pawn with a General"),
new Quote("The all-powerful joining-Pawn attack starts with Pawns in hand"),
new Quote("The beginner loves his Rook more than his King"),
new Quote("The bigger the handicap the bigger the King"),
new Quote("The Bishop's diagonal is difficult to block"),
new Quote("The board has 81 squares"),
new Quote("The Climbing Silver can be beaten"),
new Quote("The Dragon belongs in the promotion zone"),
new Quote("The enemy's vital point is your own"),
new Quote("The entering King is safe"),
new Quote("The hardest road for the Rook is dead ahead"),
new Quote("The head of a Silver is a vital square"),
new Quote("The Lance's worst enemy is a Pawn"),
new Quote("The Mino is weak against Knights"),
new Quote("The promotion sacrifice is a high-class finesse"),
new Quote("The side-stepping Knight foils the best laid plans"),
new Quote("The Silvers are the pivots of attack and defence"),
new Quote("The stab in the back is the best way to get a Gold in hand"),
new Quote("The wall Silver is bad shape"),
new Quote("The way forward is often to pull a Gold back"),
new Quote("The wrong order of moves is a good way to lose"),
new Quote("Think before you check"),
new Quote("Think before you retreat"),
new Quote("Three General make the best Royal Bodyguard"),
new Quote("Tie the King up"),
new Quote("To develop the Silver, sacrifice Pawns"),
new Quote("To play a floating Rook hurry with the edge Pawn"),
new Quote("Two Golds are better line ahead than line abreast"),
new Quote("Two Lances are better than one"),
new Quote("Watch the files where Pawns can be dropped"),
new Quote("Watch the opposing Rook"),
new Quote("Watch what the opponent is aiming at"),
new Quote("When all else fails,interpose"),
new Quote("When there is a floating piece there is always a move"),
new Quote("When you have found the best move look for a better one"),
new Quote("When your opponent plays on the right, look left"),
new Quote("With a Ranging Rook build a Mino"),
new Quote("With Pawns in hand consider an edge attack"),
new Quote("With Static Rook against Static Rook keep a Gold beside the Bishop"),

    
    // lishogi facts
    new Quote("All features for free; for everyone; forever.", "lishogi.org"),
    new Quote("We will never display ads.", "lishogi.org"),
    new Quote("We do not track you. It's a rare feature, nowadays.", "lishogi.org"),
    new Quote("Every chess player is a premium user.", "lishogi.org"),
    new Quote("I never lose. I either win or learn.", "Nelson Mandela")
  )

  implicit def quoteWriter: OWrites[Quote] =
    OWrites { q =>
      Json.obj(
        "text"   -> q.text,
        "author" -> q.author
      )
    }
}
